-- liquibase formatted sql

-- changeset init:1752747998237-1
CREATE TABLE actions (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by BIGINT NOT NULL, created_on BIGINT NOT NULL, is_active BOOLEAN DEFAULT TRUE NOT NULL, last_updated_by BIGINT, last_updated_on BIGINT, version INTEGER, deleted_on BIGINT, code VARCHAR(255) NOT NULL, description VARCHAR(255), CONSTRAINT "actionsPK" PRIMARY KEY (id));

-- changeset init:1752747998237-2
CREATE TABLE groups (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by BIGINT NOT NULL, created_on BIGINT NOT NULL, is_active BOOLEAN DEFAULT TRUE NOT NULL, last_updated_by BIGINT, last_updated_on BIGINT, version INTEGER, deleted_on BIGINT, code VARCHAR(255) NOT NULL, description VARCHAR(255), CONSTRAINT "groupsPK" PRIMARY KEY (id));

-- changeset init:1752747998237-3
CREATE TABLE permissions (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by BIGINT NOT NULL, created_on BIGINT NOT NULL, is_active BOOLEAN DEFAULT TRUE NOT NULL, last_updated_by BIGINT, last_updated_on BIGINT, version INTEGER, deleted_on BIGINT, action_id INTEGER NOT NULL, resource_type_id INTEGER NOT NULL, CONSTRAINT "permissionsPK" PRIMARY KEY (id));

-- changeset init:1752747998237-4
CREATE TABLE policies (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by BIGINT NOT NULL, created_on BIGINT NOT NULL, is_active BOOLEAN DEFAULT TRUE NOT NULL, last_updated_by BIGINT, last_updated_on BIGINT, version INTEGER, deleted_on BIGINT, code VARCHAR(255) NOT NULL, description VARCHAR(255), CONSTRAINT "policiesPK" PRIMARY KEY (id));

-- changeset init:1752747998237-5
CREATE TABLE policy_permissions (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by BIGINT NOT NULL, created_on BIGINT NOT NULL, is_active BOOLEAN DEFAULT TRUE NOT NULL, last_updated_by BIGINT, last_updated_on BIGINT, version INTEGER, deleted_on BIGINT, resource_id INTEGER, scope EFFECTIVE_SCOPE_ENUM DEFAULT 'DEFAULT' NOT NULL, permission_id INTEGER NOT NULL, policy_id INTEGER NOT NULL, CONSTRAINT "policy_permissionsPK" PRIMARY KEY (id));

-- changeset init:1752747998237-6
CREATE TABLE resource_permissions (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by BIGINT NOT NULL, created_on BIGINT NOT NULL, is_active BOOLEAN DEFAULT TRUE NOT NULL, last_updated_by BIGINT, last_updated_on BIGINT, version INTEGER, deleted_on BIGINT, scope ENFORCEMENT_SCOPE_ENUM DEFAULT 'DEFAULT' NOT NULL, permission_id INTEGER NOT NULL, resource_id INTEGER NOT NULL, CONSTRAINT "resource_permissionsPK" PRIMARY KEY (id));

-- changeset init:1752747998237-7
CREATE TABLE resource_types (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by BIGINT NOT NULL, created_on BIGINT NOT NULL, is_active BOOLEAN DEFAULT TRUE NOT NULL, last_updated_by BIGINT, last_updated_on BIGINT, version INTEGER, deleted_on BIGINT, code VARCHAR(255) NOT NULL, description VARCHAR(255), CONSTRAINT "resource_typesPK" PRIMARY KEY (id));

-- changeset init:1752747998237-8
CREATE TABLE resources (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by BIGINT NOT NULL, created_on BIGINT NOT NULL, is_active BOOLEAN DEFAULT TRUE NOT NULL, last_updated_by BIGINT, last_updated_on BIGINT, version INTEGER, deleted_on BIGINT, resource_id INTEGER NOT NULL, group_id INTEGER, resource_type_id INTEGER NOT NULL, user_id INTEGER NOT NULL, CONSTRAINT "resourcesPK" PRIMARY KEY (id));

-- changeset init:1752747998237-9
CREATE TABLE role_permissions (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by BIGINT NOT NULL, created_on BIGINT NOT NULL, is_active BOOLEAN DEFAULT TRUE NOT NULL, last_updated_by BIGINT, last_updated_on BIGINT, version INTEGER, deleted_on BIGINT, resource_id INTEGER, scope EFFECTIVE_SCOPE_ENUM DEFAULT 'DEFAULT' NOT NULL, permission_id INTEGER NOT NULL, role_id INTEGER NOT NULL, CONSTRAINT "role_permissionsPK" PRIMARY KEY (id));

-- changeset init:1752747998237-10
CREATE TABLE roles (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by BIGINT NOT NULL, created_on BIGINT NOT NULL, is_active BOOLEAN DEFAULT TRUE NOT NULL, last_updated_by BIGINT, last_updated_on BIGINT, version INTEGER, deleted_on BIGINT, code VARCHAR(255) NOT NULL, description VARCHAR(255), CONSTRAINT "rolesPK" PRIMARY KEY (id));

-- changeset init:1752747998237-11
CREATE TABLE tokens (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by BIGINT NOT NULL, created_on BIGINT NOT NULL, is_active BOOLEAN DEFAULT TRUE NOT NULL, last_updated_by BIGINT, last_updated_on BIGINT, version INTEGER, deleted_on BIGINT, device_info VARCHAR(255), expires_at BIGINT NOT NULL, ip_address VARCHAR(255), last_used_on BIGINT, login_location VARCHAR(255), token VARCHAR(255) NOT NULL, user_id INTEGER NOT NULL, CONSTRAINT "tokensPK" PRIMARY KEY (id));

-- changeset init:1752747998237-12
CREATE TABLE user_groups (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by BIGINT NOT NULL, created_on BIGINT NOT NULL, is_active BOOLEAN DEFAULT TRUE NOT NULL, last_updated_by BIGINT, last_updated_on BIGINT, version INTEGER, deleted_on BIGINT, group_id INTEGER NOT NULL, user_id INTEGER NOT NULL, CONSTRAINT "user_groupsPK" PRIMARY KEY (id));

-- changeset init:1752747998237-13
CREATE TABLE user_policies (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by BIGINT NOT NULL, created_on BIGINT NOT NULL, is_active BOOLEAN DEFAULT TRUE NOT NULL, last_updated_by BIGINT, last_updated_on BIGINT, version INTEGER, deleted_on BIGINT, policy_id INTEGER NOT NULL, user_id INTEGER NOT NULL, CONSTRAINT "user_policiesPK" PRIMARY KEY (id));

-- changeset init:1752747998237-14
CREATE TABLE user_roles (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by BIGINT NOT NULL, created_on BIGINT NOT NULL, is_active BOOLEAN DEFAULT TRUE NOT NULL, last_updated_by BIGINT, last_updated_on BIGINT, version INTEGER, deleted_on BIGINT, role_id INTEGER NOT NULL, user_id INTEGER NOT NULL, CONSTRAINT "user_rolesPK" PRIMARY KEY (id));

-- changeset init:1752747998237-15
CREATE TABLE users (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by BIGINT NOT NULL, created_on BIGINT NOT NULL, is_active BOOLEAN DEFAULT TRUE NOT NULL, last_updated_by BIGINT, last_updated_on BIGINT, version INTEGER, deleted_on BIGINT, email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, CONSTRAINT "usersPK" PRIMARY KEY (id));

-- changeset init:1752747998237-16
ALTER TABLE actions ADD CONSTRAINT UC_ACTIONSCODE_COL UNIQUE (code);

-- changeset init:1752747998237-17
ALTER TABLE groups ADD CONSTRAINT UC_GROUPSCODE_COL UNIQUE (code);

-- changeset init:1752747998237-18
ALTER TABLE policies ADD CONSTRAINT UC_POLICIESCODE_COL UNIQUE (code);

-- changeset init:1752747998237-19
ALTER TABLE resources ADD CONSTRAINT UC_RESOURCESRESOURCE_ID_COL UNIQUE (resource_id);

-- changeset init:1752747998237-20
ALTER TABLE resource_types ADD CONSTRAINT UC_RESOURCE_TYPESCODE_COL UNIQUE (code);

-- changeset init:1752747998237-21
ALTER TABLE roles ADD CONSTRAINT UC_ROLESCODE_COL UNIQUE (code);

-- changeset init:1752747998237-22
ALTER TABLE tokens ADD CONSTRAINT UC_TOKENSTOKEN_COL UNIQUE (token);

-- changeset init:1752747998237-23
ALTER TABLE users ADD CONSTRAINT UC_USERSEMAIL_COL UNIQUE (email);

-- changeset init:1752747998237-24
ALTER TABLE users ADD CONSTRAINT UC_USERSUSERNAME_COL UNIQUE (username);

-- changeset init:1752747998237-25
ALTER TABLE tokens ADD CONSTRAINT "FK2dylsfo39lgjyqml2tbe0b0ss" FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset init:1752747998237-26
ALTER TABLE resources ADD CONSTRAINT "FK4d6jo4pc9qn6bsp24l8ii8evf" FOREIGN KEY (resource_type_id) REFERENCES resource_types (id);

-- changeset init:1752747998237-27
ALTER TABLE resources ADD CONSTRAINT "FK7cheen1kwhh06bax27o7ngk1i" FOREIGN KEY (group_id) REFERENCES groups (id);

-- changeset init:1752747998237-28
ALTER TABLE user_policies ADD CONSTRAINT "FK7stwljvnp153el6s8fkmlq4ja" FOREIGN KEY (policy_id) REFERENCES policies (id);

-- changeset init:1752747998237-29
ALTER TABLE policy_permissions ADD CONSTRAINT "FKb7hi3yvsg22ybarnfofopoiq2" FOREIGN KEY (permission_id) REFERENCES permissions (id);

-- changeset init:1752747998237-30
ALTER TABLE resource_permissions ADD CONSTRAINT "FKbvp2s44j6lmye77b1wcrt3crt" FOREIGN KEY (resource_id) REFERENCES resources (id);

-- changeset init:1752747998237-31
ALTER TABLE resources ADD CONSTRAINT "FKcoba1blh4w96p6n34i4xfoiyp" FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset init:1752747998237-32
ALTER TABLE user_groups ADD CONSTRAINT "FKd37bs5u9hvbwljup24b2hin2b" FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset init:1752747998237-33
ALTER TABLE role_permissions ADD CONSTRAINT "FKegdk29eiy7mdtefy5c7eirr6e" FOREIGN KEY (permission_id) REFERENCES permissions (id);

-- changeset init:1752747998237-34
ALTER TABLE resource_permissions ADD CONSTRAINT "FKfcvil7q5kfuolloor1v5mqy90" FOREIGN KEY (permission_id) REFERENCES permissions (id);

-- changeset init:1752747998237-35
ALTER TABLE permissions ADD CONSTRAINT "FKfup5u020kx4xx7588sldyu7tm" FOREIGN KEY (resource_type_id) REFERENCES resource_types (id);

-- changeset init:1752747998237-36
ALTER TABLE user_roles ADD CONSTRAINT "FKh8ciramu9cc9q3qcqiv4ue8a6" FOREIGN KEY (role_id) REFERENCES roles (id);

-- changeset init:1752747998237-37
ALTER TABLE user_roles ADD CONSTRAINT "FKhfh9dx7w3ubf1co1vdev94g3f" FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset init:1752747998237-38
ALTER TABLE policy_permissions ADD CONSTRAINT "FKjk7khifwcg7cj5o4c3o2hd797" FOREIGN KEY (policy_id) REFERENCES policies (id);

-- changeset init:1752747998237-39
ALTER TABLE user_groups ADD CONSTRAINT "FKmrgahbb4w32n9wkjqbipttc87" FOREIGN KEY (group_id) REFERENCES groups (id);

-- changeset init:1752747998237-40
ALTER TABLE role_permissions ADD CONSTRAINT "FKn5fotdgk8d1xvo8nav9uv3muc" FOREIGN KEY (role_id) REFERENCES roles (id);

-- changeset init:1752747998237-41
ALTER TABLE permissions ADD CONSTRAINT "FKql5yu3r5kbeww3liqu42u6r84" FOREIGN KEY (action_id) REFERENCES actions (id);

-- changeset init:1752747998237-42
ALTER TABLE user_policies ADD CONSTRAINT "FKt4q4fj2srnc9ashsi1vvuit1u" FOREIGN KEY (user_id) REFERENCES users (id);

